name: CI

on: push

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      ##### BEGIN: sharable parts across jobs #####
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: cache dependencies
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: build-v0-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        # We only cache `yarn cache dir`, not including `node_modules/`.
        # thus we need to do `yarn install` to restore `node_modules/` so we need run always this step.
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
      ##### END: sharable parts across jobs #####

  build:
    needs: [install_dependencies]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      ##### BEGIN: sharable parts across jobs #####
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: cache dependencies
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: build-v0-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        # We only cache `yarn cache dir`, not including `node_modules/`.
        # thus we need to do `yarn install` to restore `node_modules/` so we need run always this step.
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
      ##### END: sharable parts across jobs #####

      - name: build
        run: make build -j
        env:
          CI: true

  build_by_esbuild:
    needs: [install_dependencies]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      ##### BEGIN: sharable parts across jobs #####
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: cache dependencies
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: build-v0-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        # We only cache `yarn cache dir`, not including `node_modules/`.
        # thus we need to do `yarn install` to restore `node_modules/` so we need run always this step.
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
      ##### END: sharable parts across jobs #####

      - name: build
        run: make build -j USE_ESBUILD=1
        env:
          CI: true

  check_formatting:
    needs: [install_dependencies]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      ##### BEGIN: sharable parts across jobs #####
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: cache dependencies
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: build-v0-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        # We only cache `yarn cache dir`, not including `node_modules/`.
        # thus we need to do `yarn install` to restore `node_modules/` so we need run always this step.
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
      ##### END: sharable parts across jobs #####

      - name: check formatting
        run: make check_format -j
        env:
          CI: true

  test:
    needs: [install_dependencies]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      ##### BEGIN: sharable parts across jobs #####
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - name: cache dependencies
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: build-v0-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        # We only cache `yarn cache dir`, not including `node_modules/`.
        # thus we need to do `yarn install` to restore `node_modules/` so we need run always this step.
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
      ##### END: sharable parts across jobs #####

      - name: test
        run: make test -j
        env:
          CI: true
